export const toolRegistry: Record<string, () => Promise<any>> = {
  'random-number': () => import('~/components/tools/numbers/RandomNumber.vue'),
  'dice-roller': () => import('~/components/tools/numbers/DiceRoller.vue'),
  'coin-flip': () => import('~/components/tools/numbers/CoinFlip.vue'),
  'lottery': () => import('~/components/tools/numbers/LotteryPicker.vue'),
  'random-date': () => import('~/components/tools/numbers/RandomDate.vue'),
  'random-time': () => import('~/components/tools/numbers/RandomTime.vue'),
  'name-picker': () => import('~/components/tools/pickers/NamePicker.vue'),
  'spin-wheel': () => import('~/components/tools/pickers/SpinWheel.vue'),
  'decision-maker': () => import('~/components/tools/pickers/DecisionMaker.vue'),
  'yes-no-oracle': () => import('~/components/tools/pickers/YesNoOracle.vue'),
  'team-generator': () => import('~/components/tools/groups/TeamGenerator.vue'),
  'group-maker': () => import('~/components/tools/groups/GroupMaker.vue'),
  'random-pairing': () => import('~/components/tools/groups/RandomPairing.vue'),
  'tournament-seeding': () => import('~/components/tools/groups/TournamentBracket.vue'),
  'password-generator': () => import('~/components/tools/strings/PasswordGenerator.vue'),
  'uuid-generator': () => import('~/components/tools/strings/UUIDGenerator.vue'),
  'lorem-ipsum': () => import('~/components/tools/strings/LoremIpsum.vue'),
  'color-generator': () => import('~/components/tools/visual/ColorGenerator.vue'),
  'gradient-generator': () => import('~/components/tools/visual/GradientGenerator.vue'),
  'identicon': () => import('~/components/tools/visual/IdenticonGen.vue'),

  'random-joke': () => import('~/components/tools/fun/JokeDisplay.vue'),
  'random-fact': () => import('~/components/tools/fun/FactDisplay.vue'),
  'random-quote': () => import('~/components/tools/fun/QuoteDisplay.vue'),

  'slot-machine': () => import('~/components/tools/interactive/SlotMachine.vue'),
  'bingo-card': () => import('~/components/tools/interactive/BingoCard.vue'),
}
